variables:
    CONTAINER_RELEASE_IMAGE: docker.rz.tu-harburg.de:5000/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
    LATEST_VERSION: '1-debian'
    CODIMD_REPOSITORY: https://${CODIMD_REPO_USER}:${CODIMD_REPO_TOKEN}@collaborating.tuhh.de/rzt/customized_oss/codimd-server.git
    SERVER_VERSION: 1.6.0+tuhh

.build_script_template:
    script:  &build_script_definition
        - pwd
        - key="CodiMD"

        - version=$(curl -s https://cgi.tu-harburg.de/~rztwww/Software/program_file.json | jq --arg KEY "$key" --raw-output '.[$KEY] | .version')
        - if [[ -z $version ]]; then exit 1; fi
        - version=$(echo $version | sed -e 's/%2B/+/g')
        - version="$version"

        # - download=$(curl -s https://cgi.tu-harburg.de/~rztwww/Software/program_file.json | jq --arg KEY "$key" --raw-output '.[$KEY] | .download')
        # - if [[ -z $download ]]; then exit 1; fi

        - sudo docker build --build-arg CODIMD_REPOSITORY=${CODIMD_REPOSITORY} --build-arg DOWNLOAD="${download}" --build-arg VERSION="${version}" --no-cache --pull -t "${CONTAINER_RELEASE_IMAGE}":"${VERSION}${VARIANT:+-$VARIANT}" -f "${VERSION}/${VARIANT}/Dockerfile"

.build_before_script_template:
    before_script:  &build_before_script_definition
        - pwd
        - git submodule update --init --recursive

.deploy_script_template:
    script:  &deploy_script_definition
        - pwd
        - sudo docker push "${CONTAINER_RELEASE_IMAGE}":"${VERSION}${VARIANT:+-$VARIANT}"
        - if [ ! -z ${LATEST_VERSION} ] && [ "${LATEST_VERSION}" == "${VERSION}${VARIANT:+-$VARIANT}" ]; then sudo docker tag "${CONTAINER_RELEASE_IMAGE}":"${VERSION}${VARIANT:+-$VARIANT}" "${CONTAINER_RELEASE_IMAGE}:latest"; sudo docker push "${CONTAINER_RELEASE_IMAGE}:latest"; fi

.build_branches_script_template:
    script:  &build_branches_script_definition
        - pwd
        - sudo docker build --pull -t "${CONTAINER_RELEASE_IMAGE}":"${VERSION}${VARIANT:+-$VARIANT}"_"${CI_COMMIT_REF_NAME}" "${VERSION}"/"${VARIANT}"

.build_branches_before_script_template:
    before_script:  &build_branches_before_script_definition
        - pwd
        - git submodule update --init --recursive

.deploy_branches_script_template:
    script:  &deploy_branches_script_definition
        - pwd
        - sudo docker push "${CONTAINER_RELEASE_IMAGE}":"${VERSION}${VARIANT:+-$VARIANT}"_"${CI_COMMIT_REF_NAME}"


stages:
    - build
    - deploy


build:1-debian:
    stage: build
    only:
        - master
    tags:
        - build
    variables:
        VERSION: '1'
        VARIANT: 'debian'
    before_script: *build_before_script_definition
    script: *build_script_definition

deploy:1-debian:
    stage: deploy
    needs: ["build:1-debian"]
    tags:
        - deploy
    only:
        - master
    variables:
        VERSION: '1'
        VARIANT: 'debian'
    script: *deploy_script_definition

build:branches:1-debian:
    stage: build
    only:
        - branches
    except:
        - master
    tags:
        - build
    variables:
        VERSION: '1'
        VARIANT: 'debian'
    before_script: *build_branches_before_script_definition
    script: *build_branches_script_definition

deploy:branches:1-debian:
    stage: deploy
    needs: ["build:branches:1-debian"]
    tags:
        - deploy
    only:
        - branches
    except:
        - master
    variables:
        VERSION: '1'
        VARIANT: 'debian'
    script: *deploy_branches_script_definition

